user_index:
    pattern: /{page}
    defaults: { _controller: TickitUserBundle:User:index, page: 1 }
    requirements:
        page: \d+

user_add:
    pattern: /add
    defaults: { _controller: TickitUserBundle:User:add }

user_edit:
    pattern: /edit/{id}
    defaults: { _controller: TickitUserBundle:User:edit }
    requirements:
        id: \d+

user_permissions_form_list:
    pattern: /permissions/form-list/{groupId}/{userId}
    defaults: { _controller: TickitUserBundle:User:permissionFormList, userId: null }
    requirements:
        groupId: \d+
        userId: \d+